# coding: utf-8

"""
    YNAB API Endpoints

    OpenAPI spec version: 1.0.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "ynab-python-client"
VERSION = "1.0.0"

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]


setup(
    name=NAME,
    version=VERSION,
    description="YNAB API Endpoints",
    author_email="",
    url="",
    keywords=["Swagger", "YNAB API Endpoints"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="YNAB API Python Client."
)
